# Generated by Django 6.1 on 2026-08-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_woundassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='woundassessment',
            name='analysis_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='woundassessment',
            name='analysis_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='woundassessment',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='woundassessment',
            name='model_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='woundassessment',
            name='wound_mask',
            field=models.ImageField(blank=True, null=True, upload_to='wound_masks/'),
        ),
    ]
