# Generated by Django 6.1 on 2026-08-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_woundassessment_analysis_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='woundassessment',
            name='wound_area_pixels',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
