# Generated by Django 6.1 on 2026-08-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_woundassessment_wound_area_pixels'),
    ]

    operations = [
        migrations.AddField(
            model_name='woundassessment',
            name='doctor_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='woundassessment',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='woundassessment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='woundassessment',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
