# Generated by Django 6.1 on 2026-08-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_woundassessment_doctor_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='woundassessment',
            name='measurement_source',
            field=models.CharField(choices=[('MANUAL_CM2', 'Manual measurement in cm²'), ('SEGMENTATION_PIXELS', 'Segmentation measurement in pixels²'), ('CALIBRATED_CM2', 'Calibrated image measurement in cm²'), ('UNKNOWN', 'Unknown / legacy')], default='UNKNOWN', max_length=30),
        ),
    ]
