"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path
import os

from dotenv import load_dotenv
import dj_database_url


# --------------------------------------------------
# BASE DIRECTORY
# --------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(
    BASE_DIR / ".env"
)


# --------------------------------------------------
# SECURITY
# --------------------------------------------------

SECRET_KEY = os.environ[
    "DJANGO_SECRET_KEY"
]

DEBUG = os.getenv(
    "DJANGO_DEBUG",
    "False"
).lower() == "true"


ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".onrender.com",
]


# --------------------------------------------------
# APPLICATIONS
# --------------------------------------------------

INSTALLED_APPS = [
    # Django applications
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party applications
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "storages",

    # Our applications
    "accounts",
    "patients",
]


# --------------------------------------------------
# MIDDLEWARE
# --------------------------------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    "whitenoise.middleware.WhiteNoiseMiddleware",

    # Allows React frontend to communicate with Django
    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# --------------------------------------------------
# URL CONFIGURATION
# --------------------------------------------------

ROOT_URLCONF = "backend.urls"


# --------------------------------------------------
# TEMPLATES
# --------------------------------------------------

TEMPLATES = [
    {
        "BACKEND":
            "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# --------------------------------------------------
# WSGI
# --------------------------------------------------

WSGI_APPLICATION = (
    "backend.wsgi.application"
)


# --------------------------------------------------
# DATABASE
# --------------------------------------------------

DATABASES = {
    "default":
        dj_database_url.config(
            default=(
                f"sqlite:///"
                f"{BASE_DIR / 'db.sqlite3'}"
            ),
            conn_max_age=600,
            conn_health_checks=True,
        )
}


# --------------------------------------------------
# PASSWORD VALIDATION
# --------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# --------------------------------------------------
# INTERNATIONALIZATION
# --------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# --------------------------------------------------
# STATIC FILES
# --------------------------------------------------

STATIC_URL = "/static/"

STATIC_ROOT = (
    BASE_DIR / "staticfiles"
)


# --------------------------------------------------
# CLOUDFLARE R2 MEDIA STORAGE
# --------------------------------------------------

R2_ACCESS_KEY_ID = os.getenv(
    "R2_ACCESS_KEY_ID"
)

R2_SECRET_ACCESS_KEY = os.getenv(
    "R2_SECRET_ACCESS_KEY"
)

R2_BUCKET_NAME = os.getenv(
    "R2_BUCKET_NAME"
)

R2_ENDPOINT_URL = os.getenv(
    "R2_ENDPOINT_URL"
)


# --------------------------------------------------
# STORAGE CONFIGURATION
# --------------------------------------------------
#
# On Render:
#   wound images and masks use Cloudflare R2.
#
# On the local computer:
#   if R2 variables are not available,
#   Django falls back to the local media folder.
# --------------------------------------------------

R2_ENABLED = all(
    [
        R2_ACCESS_KEY_ID,
        R2_SECRET_ACCESS_KEY,
        R2_BUCKET_NAME,
        R2_ENDPOINT_URL,
    ]
)


if R2_ENABLED:

    STORAGES = {
        # Uploaded wound photographs and masks
        "default": {
            "BACKEND":
                "storages.backends.s3.S3Storage",

            "OPTIONS": {
                "access_key":
                    R2_ACCESS_KEY_ID,

                "secret_key":
                    R2_SECRET_ACCESS_KEY,

                "bucket_name":
                    R2_BUCKET_NAME,

                "endpoint_url":
                    R2_ENDPOINT_URL,

                # Cloudflare R2 uses "auto"
                "region_name":
                    "auto",

                # Keep wound images private.
                "default_acl":
                    None,

                # Generate temporary signed URLs
                # when Django returns image URLs.
                "querystring_auth":
                    True,

                # Signed URL lifetime in seconds.
                "querystring_expire":
                    3600,

                # IMPORTANT:
                # Avoid the filename-availability check
                # that causes HeadObject before upload.
                "file_overwrite":
                    True,

                "signature_version":
                    "s3v4",
            },
        },

        # Django static files remain local
        # and are served through WhiteNoise.
        "staticfiles": {
            "BACKEND":
                "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

else:

    # Local development storage
    STORAGES = {
        "default": {
            "BACKEND":
                "django.core.files.storage.FileSystemStorage",
        },

        "staticfiles": {
            "BACKEND":
                "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }


# --------------------------------------------------
# LOCAL MEDIA FALLBACK
# --------------------------------------------------

MEDIA_URL = "/media/"

MEDIA_ROOT = (
    BASE_DIR / "media"
)


# --------------------------------------------------
# EMAIL
# --------------------------------------------------

EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend"
)


# --------------------------------------------------
# CORS
# --------------------------------------------------

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://wound-healing-frontend.onrender.com",
]


# --------------------------------------------------
# DJANGO REST FRAMEWORK
# --------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        (
            "rest_framework.authentication."
            "TokenAuthentication"
        ),
    ],
}