from django.db import models


class Patient(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    patient_id = models.CharField(
        max_length=50,
        unique=True
    )

    date_of_birth = models.DateField()

    sex = models.CharField(
        max_length=20
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return (
            f"{self.patient_id} - "
            f"{self.first_name} {self.last_name}"
        )


class WoundAssessment(models.Model):

    ANALYSIS_STATUS_CHOICES = [
        ("PENDING", "Pending"),
        ("COMPLETED", "Completed"),
        ("FAILED", "Failed"),
    ]

    REVIEW_STATUS_CHOICES = [
        ("PENDING", "Pending Review"),
        ("REVIEWED", "Reviewed"),
    ]

    MEASUREMENT_SOURCE_CHOICES = [
        (
            "MANUAL_CM2",
            "Manual measurement in cm²"
        ),
        (
            "SEGMENTATION_PIXELS",
            "Segmentation measurement in pixels²"
        ),
        (
            "CALIBRATED_CM2",
            "Calibrated image measurement in cm²"
        ),
        (
            "UNKNOWN",
            "Unknown / legacy"
        ),
    ]

    patient = models.ForeignKey(
        Patient,
        on_delete=models.CASCADE,
        related_name="wound_assessments"
    )

    assessment_date = models.DateField()

    # Original wound photograph
    wound_image = models.ImageField(
        upload_to="wound_images/",
        blank=True,
        null=True
    )

    # Segmentation mask generated by the analysis system
    wound_mask = models.ImageField(
        upload_to="wound_masks/",
        blank=True,
        null=True
    )

    # Raw area calculated from the segmented image
    # This value is measured in pixels².
    wound_area_pixels = models.FloatField(
        blank=True,
        null=True
    )

    # Real physical wound area in cm².
    # Used for manual or future calibrated measurements.
    wound_area = models.FloatField(
        blank=True,
        null=True
    )

    # Records how the area measurement was obtained
    measurement_source = models.CharField(
        max_length=30,
        choices=MEASUREMENT_SOURCE_CHOICES,
        default="UNKNOWN"
    )

    # Tracks the state of automatic image analysis
    analysis_status = models.CharField(
        max_length=20,
        choices=ANALYSIS_STATUS_CHOICES,
        default="PENDING"
    )

    # Confidence value from an AI model later
    analysis_confidence = models.FloatField(
        blank=True,
        null=True
    )

    # Lets us know which algorithm/model created the result
    model_version = models.CharField(
        max_length=100,
        blank=True
    )

    # Time when automatic analysis was completed
    analyzed_at = models.DateTimeField(
        blank=True,
        null=True
    )

    # Nurse or assessment notes
    notes = models.TextField(
        blank=True
    )

    # ------------------------------------------
    # DOCTOR REVIEW
    # ------------------------------------------

    review_status = models.CharField(
        max_length=20,
        choices=REVIEW_STATUS_CHOICES,
        default="PENDING"
    )

    doctor_comment = models.TextField(
        blank=True
    )

    reviewed_at = models.DateTimeField(
        blank=True,
        null=True
    )

    reviewed_by = models.CharField(
        max_length=150,
        blank=True
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return (
            f"{self.patient.patient_id} - "
            f"{self.assessment_date}"
        )